name:                aoc2018
version:             0.1.0.0
github:              "hmpcabral/aoc2018"
license:             BSD3
author:              "Henrique Cabral"
maintainer:          "henriquempcabral@gmail.com"
copyright:           "2018 Henrique Cabral"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/hmpcabral/aoc2018#readme>

dependencies:
- base
- containers
- array
- time
- pointedlist
- vector
- text
- linear

library:
  source-dirs: src

executables:
  day01-exe:
    main:                Main.hs
    source-dirs:         app01
    dependencies:
    - aoc2018
  day02-exe:
    main:                Main.hs
    source-dirs:         app02
    dependencies:
    - aoc2018
  day03-exe:
    main:                Main.hs
    source-dirs:         app03
    dependencies:
    - aoc2018
  day04-exe:
    main:                Main.hs
    source-dirs:         app04
    dependencies:
    - aoc2018
  day05-exe:
    main:                Main.hs
    source-dirs:         app05
    dependencies:
    - aoc2018
  day06-exe:
    main:                Main.hs
    source-dirs:         app06
    dependencies:
    - aoc2018
  day07-exe:
    main:                Main.hs
    source-dirs:         app07
    dependencies:
    - aoc2018
  day08-exe:
    main:                Main.hs
    source-dirs:         app08
    dependencies:
    - aoc2018
  day09-exe:
    main:                Main.hs
    source-dirs:         app09
    dependencies:
    - aoc2018
  day10-exe:
    main:                Main.hs
    source-dirs:         app10
    dependencies:
    - aoc2018
  day11-exe:
    main:                Main.hs
    source-dirs:         app11
    dependencies:
    - aoc2018
  day12-exe:
    main:                Main.hs
    source-dirs:         app12
    dependencies:
    - aoc2018
  day13-exe:
    main:                Main.hs
    source-dirs:         app13
    dependencies:
    - aoc2018
  day14-exe:
    main:                Main.hs
    source-dirs:         app14
    dependencies:
    - aoc2018
  day16-exe:
    main:                Main.hs
    source-dirs:         app16
    dependencies:
    - aoc2018

tests:
  aoc2018-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - aoc2018
    - hspec
    - QuickCheck
